/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculater.cal.code;

/**
 *
 * @author sajeewa
 */
public class main extends javax.swing.JFrame {
    String enternumber ="";
    double total ;
    double fristnumber ;
    double secondnumber ;
    String operation;
    

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        textdisplay = new javax.swing.JTextField();
        btn0 = new javax.swing.JButton();
        btnca = new javax.swing.JButton();
        btnce = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnfloat = new javax.swing.JButton();
        enter = new javax.swing.JButton();
        ekathu = new javax.swing.JButton();
        adu = new javax.swing.JButton();
        wedi = new javax.swing.JButton();
        bedima = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textdisplay.setBackground(new java.awt.Color(255, 255, 255));
        textdisplay.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        textdisplay.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(textdisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 110));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 440, 110));

        btn0.setBackground(new java.awt.Color(102, 102, 102));
        btn0.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn0.setForeground(new java.awt.Color(255, 255, 255));
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel2.add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 160, 30));

        btnca.setText("CA");
        btnca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncaActionPerformed(evt);
            }
        });
        jPanel2.add(btnca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 70, 30));

        btnce.setText("CE");
        btnce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnceActionPerformed(evt);
            }
        });
        jPanel2.add(btnce, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 70, 30));

        btn2.setBackground(new java.awt.Color(102, 102, 102));
        btn2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn2.setForeground(new java.awt.Color(255, 255, 255));
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 70, 30));

        btn1.setBackground(new java.awt.Color(102, 102, 102));
        btn1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 70, 30));

        btn3.setBackground(new java.awt.Color(102, 102, 102));
        btn3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn3.setForeground(new java.awt.Color(255, 255, 255));
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel2.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 70, 30));

        btn6.setBackground(new java.awt.Color(102, 102, 102));
        btn6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn6.setForeground(new java.awt.Color(255, 255, 255));
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel2.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 70, 30));

        btn5.setBackground(new java.awt.Color(102, 102, 102));
        btn5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn5.setForeground(new java.awt.Color(255, 255, 255));
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel2.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 70, 30));

        btn4.setBackground(new java.awt.Color(102, 102, 102));
        btn4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn4.setForeground(new java.awt.Color(255, 255, 255));
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel2.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 70, 30));

        btn7.setBackground(new java.awt.Color(102, 102, 102));
        btn7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn7.setForeground(new java.awt.Color(255, 255, 255));
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel2.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 70, 30));

        btn8.setBackground(new java.awt.Color(102, 102, 102));
        btn8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn8.setForeground(new java.awt.Color(255, 255, 255));
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel2.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 70, 30));

        btn9.setBackground(new java.awt.Color(102, 102, 102));
        btn9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn9.setForeground(new java.awt.Color(255, 255, 255));
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel2.add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 70, 30));

        btnfloat.setBackground(new java.awt.Color(102, 102, 102));
        btnfloat.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnfloat.setForeground(new java.awt.Color(255, 255, 255));
        btnfloat.setText(".");
        btnfloat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfloatActionPerformed(evt);
            }
        });
        jPanel2.add(btnfloat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 70, 30));

        enter.setText("=");
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });
        jPanel2.add(enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 130, 30));

        ekathu.setText("+");
        ekathu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekathuActionPerformed(evt);
            }
        });
        jPanel2.add(ekathu, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 80, 30));

        adu.setText("-");
        adu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aduActionPerformed(evt);
            }
        });
        jPanel2.add(adu, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 80, 30));

        wedi.setText("*");
        wedi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wediActionPerformed(evt);
            }
        });
        jPanel2.add(wedi, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 80, 30));

        bedima.setText("/");
        bedima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bedimaActionPerformed(evt);
            }
        });
        jPanel2.add(bedima, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        enternumber = textdisplay.getText() + btn4.getText(); 
        textdisplay.setText(enternumber);
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        enternumber = textdisplay.getText() + btn8.getText(); 
        textdisplay.setText(enternumber);
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        enternumber = textdisplay.getText() + btn9.getText(); 
        textdisplay.setText(enternumber);
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        enternumber = textdisplay.getText() + btn1.getText(); 
        textdisplay.setText(enternumber);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        enternumber = textdisplay.getText() + btn2.getText(); 
        textdisplay.setText(enternumber);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        enternumber = textdisplay.getText() + btn3.getText(); 
        textdisplay.setText(enternumber);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        enternumber = textdisplay.getText() + btn5.getText(); 
        textdisplay.setText(enternumber);
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        enternumber = textdisplay.getText() + btn6.getText(); 
        textdisplay.setText(enternumber);
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        enternumber = textdisplay.getText() + btn7.getText(); 
        textdisplay.setText(enternumber);
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        enternumber = textdisplay.getText() + btn0.getText(); 
        textdisplay.setText(enternumber);
    }//GEN-LAST:event_btn0ActionPerformed

    private void ekathuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekathuActionPerformed
        fristnumber = Double.parseDouble(textdisplay.getText());
        textdisplay.setText("");
        operation = "+";
    }//GEN-LAST:event_ekathuActionPerformed

    private void aduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aduActionPerformed
        fristnumber = Double.parseDouble(textdisplay.getText());
        textdisplay.setText("");
        operation = "-";
    }//GEN-LAST:event_aduActionPerformed

    private void wediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wediActionPerformed
        fristnumber = Double.parseDouble(textdisplay.getText());
        textdisplay.setText("");
        operation = "*";
    }//GEN-LAST:event_wediActionPerformed

    private void bedimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bedimaActionPerformed
        fristnumber = Double.parseDouble(textdisplay.getText());
        textdisplay.setText("");
        operation = "/";
    }//GEN-LAST:event_bedimaActionPerformed

    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
        String ans;
        secondnumber = Double.parseDouble(textdisplay.getText());
        total = fristnumber+secondnumber;
        
        if (operation == "+") {
            total = fristnumber+secondnumber;
            ans = String.format("%f", total);
            textdisplay.setText(ans);
            
        }else if (operation == "-") {
            total = fristnumber-secondnumber;
            ans = String.format("%f", total);
            textdisplay.setText(ans);
            
        }else if (operation == "*") {
            total = fristnumber*secondnumber;
            ans = String.format("%f", total);
            textdisplay.setText(ans);
            
        }else if (operation == "/") {
            total = fristnumber/secondnumber;
            ans = String.format("%f", total);
            textdisplay.setText(ans);
        }

        
        
    }//GEN-LAST:event_enterActionPerformed

    private void btnfloatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfloatActionPerformed
        enternumber = textdisplay.getText() + btnfloat.getText(); 
        textdisplay.setText(enternumber);
    }//GEN-LAST:event_btnfloatActionPerformed

    private void btncaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncaActionPerformed
        textdisplay.setText("");
    }//GEN-LAST:event_btncaActionPerformed

    private void btnceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnceActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adu;
    private javax.swing.JButton bedima;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnca;
    private javax.swing.JButton btnce;
    private javax.swing.JButton btnfloat;
    private javax.swing.JButton ekathu;
    private javax.swing.JButton enter;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField textdisplay;
    private javax.swing.JButton wedi;
    // End of variables declaration//GEN-END:variables
}
